### ISSUE TITLE
Blocking error - current .NET SDK does not support targeting 

### ISSUE THREAD

**Issue by Firewaterrunoff** [minis-patchers/SynFloraFix#1]
C:\ProgramFiles\dotnet\sdk\5.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 6.0.  Either target .NET Core 5.0 or lower, or use a version of the .NET SDK that supports .NET Core 6.0.

**Comment by Minizbot2012** [comment]
You need to install the net 6 sdk from https://dotnet.microsoft.com/en-us/download
I will not be reverting the change as synthesis should be upgrading to net 6 in the near future.
