### ISSUE TITLE
Which files from Nexus do we need?

### ISSUE THREAD

**Issue by ghyujkilop** [minis-patchers/SynFloraFix#3]
Also, if we use [Wiseman303's Flora Fixes - Revamped](https://www.nexusmods.com/skyrimspecialedition/mods/28197) would your patcher be helpful at all?

**Comment by Minizbot2012** [comment]
Nay, the files from nexus are: https://www.nexusmods.com/skyrimspecialedition/mods/42057
The patcher has a safeguard from duplicating scripts,
running wiseman's (the version with scripts) in tandem would disable the scripted parts of this Patcher for all but non vanilla plants

**Comment by ghyujkilop** [comment]
> Nay, the files from nexus are: https://www.nexusmods.com/skyrimspecialedition/mods/42057 The patcher has a safeguard from duplicating scripts, running wiseman's (the version with scripts) in tandem would disable the scripted parts of this Patcher for all but non vanilla plants

So, would you suggest we uise wisemans version? or just use your version to remove any problems in our game? I'd like to know which is best, which would likely cause less performance issues & game sisues.

**Comment by Minizbot2012** [comment]
> 

If you want to use wiseman's extra fixes, use the unscripted version from the nexus. The way this is configured is that if scripts are attached to the record, it will not attach my script.

**Comment by ghyujkilop** [comment]
Sweet, done!
